version: "3.8"

services:
  jedi:
    container_name: jedi_backend
    build:
      context: ./jedi
    ports:
      - 8080:8080
    volumes:
      - ${HOME}/jedi-arquivos/documentos:/home/app/jedi-arquivos/documentos
    env_file:
      - .env
    environment:
      APP_BASE_URL: ${APP_BASE_URL}
    logging:
      options:
        max-size: 10m
    networks:
      - jedi-network

  psql:
    container_name: psql
    image: postgres:alpine3.19
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    networks:
      - jedi-network

networks:
  jedi-network:
    driver: bridge
