services:
  jedi:
    container_name: jedi_backend
    build:
      context: ./jedi
    ports:
      - 8080:8080
    environment:
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    logging:
      options:
        max-size: 10m
    networks:
      - jedi-network

  psql:
    container_name: psql
    image: postgres:alpine3.19
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    networks:
      - jedi-network

networks:
  jedi-network:
    driver: bridge
