CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SEQUENCE IF NOT EXISTS banners_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS base_section_item_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS blog_items_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS blog_sections_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS contact_form_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS contact_us_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS content_section_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS faq_items_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS faq_sections_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS presentation_sections_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS rede_jedi_image_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS rede_jedi_section_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS team_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE banner_item
(
    button_text VARCHAR(255),
    button_url  VARCHAR(255),
    id          BIGINT NOT NULL,
    banner_id   BIGINT,
    CONSTRAINT banner_item_pkey PRIMARY KEY (id)
);

CREATE TABLE banners
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255),
    title       VARCHAR(255),
    CONSTRAINT banners_pkey PRIMARY KEY (id)
);

CREATE TABLE base_section_item
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_name VARCHAR(255),
    img_url   VARCHAR(255),
    CONSTRAINT base_section_item_pkey PRIMARY KEY (id)
);

CREATE TABLE blog_items
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    author                    VARCHAR(255),
    cloudinary_public_id      VARCHAR(255),
    date                      VARCHAR(255),
    description               OID,
    icon_cloudinary_public_id VARCHAR(255),
    icon_url                  VARCHAR(255),
    image_description         VARCHAR(255),
    image_url                 VARCHAR(255),
    reading_time              VARCHAR(255),
    title                     VARCHAR(255),
    blog_section_id           BIGINT,
    CONSTRAINT blog_items_pkey PRIMARY KEY (id)
);

CREATE TABLE blog_sections
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(255),
    CONSTRAINT blog_sections_pkey PRIMARY KEY (id)
);

CREATE TABLE contact_form
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    city          VARCHAR(255),
    email         VARCHAR(255)                            NOT NULL,
    message       VARCHAR(255),
    name          VARCHAR(255)                            NOT NULL,
    subject       VARCHAR(255),
    contact_us_id BIGINT,
    CONSTRAINT contact_form_pkey PRIMARY KEY (id)
);

CREATE TABLE contact_us
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description     VARCHAR(255),
    sub_title       VARCHAR(255),
    title           VARCHAR(255),
    contact_form_id BIGINT,
    CONSTRAINT contact_us_pkey PRIMARY KEY (id)
);

CREATE TABLE content_item
(
    img_text   VARCHAR(255),
    id         BIGINT NOT NULL,
    content_id BIGINT,
    CONSTRAINT content_item_pkey PRIMARY KEY (id)
);

CREATE TABLE content_section
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description     VARCHAR(255),
    file_name       VARCHAR(255),
    main_image_text VARCHAR(255),
    main_image_url  VARCHAR(255),
    sub_title       VARCHAR(255),
    title           VARCHAR(255),
    CONSTRAINT content_section_pkey PRIMARY KEY (id)
);

CREATE TABLE faq_items
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    answer         VARCHAR(255),
    position       INTEGER,
    question       VARCHAR(255),
    faq_section_id BIGINT,
    CONSTRAINT faq_items_pkey PRIMARY KEY (id)
);

CREATE TABLE faq_sections
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    subtitle VARCHAR(255),
    title    VARCHAR(255),
    CONSTRAINT faq_sections_pkey PRIMARY KEY (id)
);

CREATE TABLE header
(
    id                   UUID NOT NULL,
    button_text          VARCHAR(255),
    cloudinary_public_id VARCHAR(255),
    logo_url             VARCHAR(255),
    text1                VARCHAR(255),
    text2                VARCHAR(255),
    text3                VARCHAR(255),
    text4                VARCHAR(255),
    CONSTRAINT header_pkey PRIMARY KEY (id)
);

CREATE TABLE pre_inscricao
(
    id                  UUID NOT NULL,
    accepted_terms      BOOLEAN      NOT NULL,
    birth_date          date,
    cell_phone          VARCHAR(255) NOT NULL,
    complete_name       VARCHAR(255),
    continuation_token  VARCHAR(255),
    cpf                 VARCHAR(255),
    document_url        VARCHAR(255),
    email               VARCHAR(255) NOT NULL,
    municipality        VARCHAR(255),
    proof_of_adress_url VARCHAR(255),
    rg                  VARCHAR(255),
    status              VARCHAR(255),
    token_expiration    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pre_inscricao_pkey PRIMARY KEY (id)
);

CREATE TABLE presentation_sections
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_name          VARCHAR(255),
    first_description  VARCHAR(255),
    first_statistic    VARCHAR(255),
    img_description    VARCHAR(255),
    img_url            VARCHAR(255),
    second_description VARCHAR(255),
    second_statistic   VARCHAR(255),
    title              VARCHAR(255),
    CONSTRAINT presentation_sections_pkey PRIMARY KEY (id)
);

CREATE TABLE rede_jedi_image
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_name  VARCHAR(255),
    url        VARCHAR(255),
    section_id BIGINT,
    CONSTRAINT rede_jedi_image_pkey PRIMARY KEY (id)
);

CREATE TABLE rede_jedi_section
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo VARCHAR(255),
    CONSTRAINT rede_jedi_section_pkey PRIMARY KEY (id)
);

CREATE TABLE team
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(255),
    CONSTRAINT team_pkey PRIMARY KEY (id)
);

CREATE TABLE team_items
(
    id      BIGINT NOT NULL,
    team_id BIGINT,
    CONSTRAINT team_items_pkey PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         UUID NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    login      VARCHAR(255),
    name       VARCHAR(255),
    password   VARCHAR(255),
    photo_url  VARCHAR(255),
    role       VARCHAR(255),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE contact_us
    ADD CONSTRAINT uk3xemeu70f20qtq7ulll4xvjkj UNIQUE (contact_form_id);

ALTER TABLE contact_form
    ADD CONSTRAINT ukaycd6urycm673uni6opr32k40 UNIQUE (contact_us_id);

ALTER TABLE pre_inscricao
    ADD CONSTRAINT ukee2kj3svumpnec0t0oe03xltf UNIQUE (continuation_token);

ALTER TABLE contact_form
    ADD CONSTRAINT ukiyd1jis4d5h99vurs5se1gr42 UNIQUE (email);

ALTER TABLE pre_inscricao
    ADD CONSTRAINT ukpwtih0p1t1lemtd3nxcw1jufn UNIQUE (email);

ALTER TABLE banner_item
    ADD CONSTRAINT fk17dta71hra9m6qtqcy4fpo4o0 FOREIGN KEY (banner_id) REFERENCES banners (id) ON DELETE NO ACTION;

ALTER TABLE rede_jedi_image
    ADD CONSTRAINT fk1x1x0nbi2dmjnuww7eh6g9ems FOREIGN KEY (section_id) REFERENCES rede_jedi_section (id) ON DELETE NO ACTION;

ALTER TABLE blog_items
    ADD CONSTRAINT fk4teh15pfi5qvjsstk1tx0rm2b FOREIGN KEY (blog_section_id) REFERENCES blog_sections (id) ON DELETE NO ACTION;

ALTER TABLE content_item
    ADD CONSTRAINT fkd8ncqjvfqcjaqrfr0ke7vi3pb FOREIGN KEY (content_id) REFERENCES content_section (id) ON DELETE NO ACTION;

ALTER TABLE content_item
    ADD CONSTRAINT fkk3k9jspssinjq8n55gadlwf91 FOREIGN KEY (id) REFERENCES base_section_item (id) ON DELETE NO ACTION;

ALTER TABLE faq_items
    ADD CONSTRAINT fkl3gosjvqrt6xqsrhc4akxl7nw FOREIGN KEY (faq_section_id) REFERENCES faq_sections (id) ON DELETE NO ACTION;

ALTER TABLE contact_us
    ADD CONSTRAINT fkn5va1p5heluuohcbdtlprj0ei FOREIGN KEY (contact_form_id) REFERENCES contact_form (id) ON DELETE NO ACTION;

ALTER TABLE team_items
    ADD CONSTRAINT fknagb1ru86e3qlpvk5g5lf707j FOREIGN KEY (team_id) REFERENCES team (id) ON DELETE NO ACTION;

ALTER TABLE team_items
    ADD CONSTRAINT fkomi2pv1ni2w5w3dsti3lx8vax FOREIGN KEY (id) REFERENCES base_section_item (id) ON DELETE NO ACTION;

ALTER TABLE banner_item
    ADD CONSTRAINT fkp7ai0p0246rqrjsy3lkc3buoi FOREIGN KEY (id) REFERENCES base_section_item (id) ON DELETE NO ACTION;

ALTER TABLE contact_form
    ADD CONSTRAINT fkqd2m1dcp58xxovxf1wdoh4dof FOREIGN KEY (contact_us_id) REFERENCES contact_us (id) ON DELETE NO ACTION;