name: CI - Jedi Back

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: [ubuntu-latest, back-jedi-runner]

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Criar arquivo .env com secrets
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env

