name: CI - Jedi Back

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: [self-hosted, back-jedi-runner]

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Criar arquivo .env a partir dos secrets
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env

      - name: Verificar configuração do docker-compose
        run: docker-compose -f docker-compose.yml config

      - name: Build dos containers
        run: docker-compose -f docker-compose.yml build

      - name: Subir os containers
        run: docker-compose -f docker-compose.yml up -d

      - name: Exibir containers ativos (debug)
        run: docker ps

